### ISSUE TITLE
Can't get to work on Realme 7 Pro

### ISSUE THREAD

**Issue by filip-769** [rapperskull/realme_gps_l5_enabler#1]
Hi, i think i need help with getting this to work. I installed the v0.0.3 on Magisk 27.0, Android 11, LineageOS 18.1.

This is the error:
```
RealmeGPSL5Enabler v0.0.3 by Rapper_skull

Slot:

ls: /dev/block/bootdevice/by-name/oplusstanvbk: No such file or directory

ERROR: /dev/block/bootdevice/by-name/oplusstanvbk doesn't exist!!!
```

This is `ls` of `/dev/block/bootdevice/by-name/` (I don't know if that helps):
```
ALIGN_TO_128K_1  featenabler     opporeserve2
ALIGN_TO_128K_2  featenablerbak  opporeserve3
DRIVER           frp             oppostanvbk
abl              fsc             persist
ablbak           fsg             preload
aop              hyp             qupfw
aopbak           hypbak          qupfwbak
apdp             imagefv         rawdump
bluetooth        imagefvbak      recovery
bluetoothbak     keymaster       recoverybak
boot             keymasterbak    secdata
bootbak          keystore        splash
cache            limits          spunvm
catecontentfv    logdump         ssd
catefv           logfs           storsec
cateloader       mdtp            super
cdt              mdtpbak         toolsfv
cdt_engineering  mdtpsecapp      tz
cmnlib           mdtpsecappbak   tzbak
cmnlib64         metadata        uefisecapp
cmnlib64bak      misc            uefisecappbak
cmnlibbak        modem           uefivarstore
custom           modemst1        userdata
ddr              modemst2        vbmeta
devcfg           msadp           vbmeta_system
devcfgbak        multiimgoem     vbmeta_vendor
devinfo          multiimgqti     vbmetabak
dip              ocdt            xbl
dsp              odm             xbl_config
dspbak           oppo_sec        xbl_configbak
dtbo             oppodycnvbk     xblbak
dtbobak          opporeserve1
```

I would really like to get dual band to work to improve the accuracy a bit.

**Comment by rapperskull** [comment]
This is because there's no `oplusstanvbk` partition. I see that there's a partition called `oppostanvbk`, but after downloading the firmware for your phone, I see that the format is completely different, so there's no way my module would work.

Also, keep in mind that, even if your processor supports it, your phone might not have the needed hardware and/or software to support dual-band GPS.

I'm afraid I can't help you with that.

**Comment by filip-769** [comment]
I found out my phone supports L5 without this module. I just need to hold it horizontally. I have no idea why but i only get like a third of satellites and much lower accuracy while holding it vertically. Probably antenna or another hardware issue. Thank you a lot for looking into this.
